INSERT INTO `group_units` (`name`, `id_group_components`) VALUES ('Социально-гуманитарный модуль 1', 1);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('История', 'shifr', 1);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Политология', 'shifr', 1);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Философия', 'shifr', 1);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Экономика', 'shifr', 1);
INSERT INTO `group_units` (`name`, `id_group_components`) VALUES ('Модуль естественно-научных дисциплин', 1);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Высшая математика', 'shifr', 2);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Физика', 'shifr', 2);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Общая неорганическая и физическая химия', 'shifr', 2);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Начертательная геометрия, инженерная и машинная графика', 'shifr', 2);
INSERT INTO `group_units` (`name`, `id_group_components`) VALUES ('Модуль «Языковое использование»', 1);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Иностранный язык', 'shifr', 3);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Белорусский язык (профессиональная лексика)', 'shifr', 3);
INSERT INTO `group_units` (`name`, `id_group_components`) VALUES ('Модуль «Электроника»', 1);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Теоретические основы электротехники', 'shifr', 4);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Электроника', 'shifr', 4);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Курсовая работа по учебной дисциплине «Электроника»', 'shifr', 4);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Электронные устройства автоматики', 'shifr', 4);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Курсовой проект по учебной дисциплине «Электронные устройства автоматики»', 'shifr', 4);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Микропроцессорная техника систем автоматизации', 'shifr', 4);
INSERT INTO `group_units` (`name`, `id_group_components`) VALUES ('Модуль «Безопасность жизнедеятельности»', 1);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Безопасность жизнедеятельности человека', 'shifr', 5);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Охрана труда', 'shifr', 5);
INSERT INTO `group_units` (`name`, `id_group_components`) VALUES ('Модуль «Экономика и энергосбережение»', 1);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Экономика отрасли', 'shifr', 6);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Энергосбережение и энергетический менеджмент', 'shifr', 6);
INSERT INTO `group_units` (`name`, `id_group_components`) VALUES ('Социально-гуманитарный модуль 2', 2);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('История науки и техники / Психология труда', 'shifr', 7);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Теория экономических систем / Основы права', 'shifr', 7);
INSERT INTO `group_units` (`name`, `id_group_components`) VALUES ('Модуль «Организация производства»', 2);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Организация производства и управление предприятием', 'shifr', 8);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Автоматизированные системы управления производством', 'shifr', 8);
INSERT INTO `group_units` (`name`, `id_group_components`) VALUES ('Модуль «Материалы и механика»', 2);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Теоретическая механика', 'shifr', 9);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Материаловедение и обработка материалов', 'shifr', 9);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Прикладная механика', 'shifr', 9);
INSERT INTO `group_units` (`name`, `id_group_components`) VALUES ('Модуль «Приводы»', 2);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Гидравлика и гидропневмопривод', 'shifr', 10);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Автоматизированный электропривод отрасли', 'shifr', 10);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Курсовая работа по учебной дисциплине «Автоматизированный электропривод отрасли»', 'shifr', 10);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Теплотехника', 'shifr', 10);
INSERT INTO `group_units` (`name`, `id_group_components`) VALUES ('Модуль «Математические основы управления»', 2);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Теория автоматического управления', 'shifr', 11);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Курсовая работа по учебной дисциплине «Теория автоматического управления»', 'shifr', 11);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Математические модели', 'shifr', 11);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Моделирование объектов и систем автоматизации', 'shifr', 11);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Курсовая работа по учебной дисциплине «Моделирование объектов и систем автоматизации»', 'shifr', 11);
INSERT INTO `group_units` (`name`, `id_group_components`) VALUES ('Модуль «Системы автоматизации»', 2);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Метрология, методы и приборы технических измерений', 'shifr', 12);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Курсовая работа по учебной дисциплине «Метрология, методы и приборы технических измерений»', 'shifr', 12);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Технические устройства автоматизации', 'shifr', 12);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Курсовой проект по учебной дисциплине «Технические устройства автоматизации»', 'shifr', 12);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Проектирование систем автоматизации', 'shifr', 12);
INSERT INTO `group_units` (`name`, `id_group_components`) VALUES ('Модуль «Автоматизация отрасли»', 2);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Технологические процессы и аппараты отрасли', 'shifr', 13);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Системы автоматизированного проектирования отрасли', 'shifr', 13);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Автоматизация технологических процессов отрасли', 'shifr', 13);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Курсовой проект по учебной дисциплине «Автоматизация технологических процессов отрасли»', 'shifr', 13);
INSERT INTO `group_units` (`name`, `id_group_components`) VALUES ('Модуль «Применение систем автоматизации»', 2);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Мехатроника и автоматизация средств механизации', 'shifr', 14);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Монтаж, эксплуатация и диагностика систем автоматизации', 'shifr', 14);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Курсовая работа по учебной дисциплине «Монтаж, эксплуатация и диагностика систем автоматизации»', 'shifr', 14);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Интеллектуальные сенсорные устройства / Вычислительные промышленные сети и средства связи', 'shifr', 14);
INSERT INTO `group_units` (`name`, `id_group_components`) VALUES ('Модуль «Информационные технологии»', 2);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Информатика и компьютерная графика', 'shifr', 15);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Основы компьютеризации технологий в системах автоматики', 'shifr', 15);
INSERT INTO `subject` (`name`,`shifr`,`id_unit`) VALUES ('Основы объектно-ориентированного программирования / Базы данных в системах автоматики', 'shifr', 15);
INSERT INTO `group_units` (`name`, `id_group_components`) VALUES ('Физическая культура (группы спортивной специализации)', 3);
INSERT INTO `group_units` (`name`, `id_group_components`) VALUES ('Деловой иностранный язык', 3);
INSERT INTO `group_units` (`name`, `id_group_components`) VALUES ('Физическая культура', 4);
INSERT INTO `group_units` (`name`, `id_group_components`) VALUES ('Военная подготовка', 4);
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('УК-1', 'Знать закономерности исторического развития и формирования государственных и общественных институтов белорусского этноса, особенности развития науки, техники и технологий в разные исторические периоды, быть способным анализировать процессы государственного строительства и определять социально-политическое значение исторических событий, личностей, артефактов и символов');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('УК-2', 'Владеть высоким уровнем культуры политического мышления и поведения, понимать сущность, ценности и принципы идеологии белорусского государства, анализировать социально-политические процессы в стране и мире');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('УК-3', 'Владеть культурой мышления, быть способным к восприятию, обобщению и анализу информации, философских, мировоззренческих и психолого-педагогических проблем в сфере межличностных отношений и профессиональной деятельности ');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('УК-4', 'Уметь анализировать и оценивать социально-значимые явления, события и процессы, использовать социологическую и экономическую информацию при решении аналитических, научных и профессиональных задач, быть способным к проявлению предпринимательской инициативы ');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('УК-5', 'Обладать базовыми навыками коммуникации в устной и письменной формах на государственном и иностранном языках для решения задач межличностного и межкультурного взаимодействия и производственных задач');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('УК-6', 'Владеть навыками здоровьесбережения');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('УК-7', 'Владеть основами психологии труда для решения задач профессиональной деятельности');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('УК-8', 'Быть способным использовать основы правовых знаний в различных сферах жизнедеятельности, владеть навыками поиска нормативных правовых актов, анализа их содержания и применения для решения профессиональных задач');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('БПК-1', 'Владеть основными понятиями и методами линейной алгебры, аналитической и векторной геометрии, математического анализа, дифференциального и интегрального исчислений, анализа функций одной и нескольких переменных,  применять полученные знания для решения прикладных, инженерных задач');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('БПК-2', 'Владеть основными понятиями и законами физики, принципами экспериментального и теоретического изучения физических явлений и процессов, быть способным создавать и анализировать на основе физических законов теоретические модели, владеть навыками практического использования принципов и приемов физических измерений');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('БПК-3', 'Владеть теоретическими положениями химии, техникой химических расчетов и методами химических экспериментальных исследований, быть способным прогнозировать свойства соединений на основании строения вещества, характера химического и межмолекулярного взаимодействия ');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('БПК-4', 'Владеть методами защиты производственного персонала и населения от негативных воздействий факторов антропогенного, техногенного, естественного происхождения, знаниями основ рационального природопользования и энергосбережения  ');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('БПК-5', 'Быть способным применять в профессиональной деятельности правовые, организационные и инженерные основы обеспечения безопасных и здоровых условий труда, производить оценку условий труда, выявлять опасные и вредные производственные факторы, принимать решения по нормализации условий труда');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('БПК-6', 'Владеть методами графического изображения предметов на плоскости и в пространстве, навыками использования современного программного обеспечения для работы с графической информацией');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('БПК-7', 'Владеть базовыми навыками расчетов и испытаний электрических схем электрооборудования');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('БПК-8', 'Владеть инженерными методиками расчета, проектирования электронных устройств различного назначения, а также применения основных типов современных аналоговых и цифровых интегральных микросхем для решения инженерных задач');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('БПК-9', 'Быть способным производить расчеты и разрабатывать электронные средства автоматизации');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('БПК-10', 'Быть способным внедрять современные микропроцессорные системы автоматизации, осуществлять переналадку оборудования');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('БПК-11', 'Быть способным использовать основы экономических знаний в сфере лёгкой промышленности и других областях');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('БПК-12', 'Быть способным применять прогрессивные энергоэффективные и ресурсосберегающие технологии монтажа и наладки средств автоматизации');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('СК-1', 'Быть способным формировать стратегию управления производством, осуществлять  организационно-технические расчеты для планирования  основного и вспомогательного производств, выполнять оценку эффективности мероприятий по техническому и организационному развитию производства ');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('СК-2', 'Владеть основами организации, структуры и функционирования автоматизированных систем управления производством');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('СК-3', 'Быть способным применять физико-математические методы для расчетов механизмов, машин и конструкций, разрабатывать и анализировать их кинематические и динамические схемы');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('СК-4', 'Владеть основами состава, строения, свойств и обработки материалов');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('СК-5', 'Быть способным производить расчеты технических конструкций и их элементов на прочность, устойчивость, жесткость, знать устройство и принципы взаимодействия деталей машин общего назначения, определять рациональные варианты передач приводов машин и механизмов');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('СК-6', 'Быть способным выполнять расчет систем автоматизированного гидропневмопривода для использования в системах автоматизации');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('СК-7', 'Быть способным выполнять расчет систем автоматизированного электропривода для использования в системах автоматизации отрасли');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('СК-8', 'Быть способным осуществлять  расчет теплообмена в теплотехнологических процессах и аппаратах');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('СК-9', 'Владеть методиками расчета, оценки параметров систем автоматического управления');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('СК-10', 'Владеть методиками построения математических моделей');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('СК-11', 'Быть способным идентифицировать и определять коэффициенты моделей различных объектов и процессов, а также проводить их оптимизацию.');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('СК-12', 'Быть способным применять методики измерения технологических параметров с использованием современных средств и приборов технических измерений ');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('СК-13', 'Быть способным выбирать технические средства автоматизации для решения различных инженерных задач ');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('СК-14', 'Быть способным производить расчеты и проектирование отдельных частей и систем автоматизации и управления');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('СК-15', 'Быть способным выполнять расчет технологического оборудования отрасли');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('СК-16', 'Быть способным применять современные системы автоматизированного проектирования систем управления ');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('СК-17', 'Быть способным выполнять комплексную автоматизацию технологических процессов отрасли');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('СК-18', 'Быть способным выполнять расчет и использовать мехатронные системы для решения инженерных задач');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('СК-19', 'Быть способным планировать и производить монтаж, диагностику и поддерживать работоспособность систем автоматизации');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('СК-20', 'Быть способным использовать современные интеллектуальные сенсорные устройства для решения инженерных задач');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('СК-21', 'Быть способным использовать современные телекоммуникационные технологии для решения инженерных задач');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('СК-22', 'Владеть методами, способами и средствами получения, хранения и обработки информации (в том числе и графической)');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('СК-23', 'Быть способным применять современные программно-аппаратные системы в системах автоматики');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('СК-24', 'Владеть объектно-ориентированным языком программирования и навыками его применения для решения задач в области автоматизации ');
INSERT INTO `competence` (`code`, `name_competence`) VALUES ('СК-25', 'Владеть методами и средствами разработки и использования современных хранилищ данных для решения задач в области автоматизации');
